### ISSUE TITLE
Allow configuring urgency with notify-send for failed commands

### ISSUE THREAD

**Issue by nzig** [franciscolourenco/done#103]
Currently, you can set `__done_notification_urgency_level` to decide the urgency of the notification. However, if the command fails the urgency level is overwritten with `critical`. I would like for this to be configurable as well.

I thought of adding an additional configuration option: `__done_notification_urgency_level_failure` for this.

**Comment by franciscolourenco** [comment]
Available in https://github.com/franciscolourenco/done/releases/tag/1.16.0
