### ISSUE TITLE
Ability to set notification timeout

### ISSUE THREAD

**Issue by alterae** [franciscolourenco/done#114]
Using the sway window manager with the mako notification daemon.

It would be nice if there was a way to get `done` notifications to automatically disappear after a certain amount of time.

**Comment by ammgws** [comment]
Have you tried playing around with your `mako` config?

I have this in mine which IIRC was so the notifications would persist, so try changing the settings:
```ini
[app-name=fish]
ignore-timeout=1
default-timeout=0
```

**Comment by Alterae** [comment]
> Have you tried playing around with your `mako` config?
> 
> I have this in mine which IIRC was so the notifications would persist, so try changing the settings:
> ```ini
> [app-name=fish]
> ignore-timeout=1
> default-timeout=0
> ```

That worked, thank you!

The options I used:

```ini
[app-name=fish]
default-timeout=5000
```

(At least for my use case I don't need to set `ignore-timeout`)
