### ISSUE TITLE
Wrong parameter names in README

### ISSUE THREAD

**Issue by frazar** [franciscolourenco/done#119]
As of commit a2b53cb6efaab2cc24b3b8ae9498b6d4d6e8fc06, the name of all configuration variables use a single underscore as prefix rather than two. For example, `__done_min_cmd_duration` has become `_done_min_cmd_duration`.

However, the README has not been updated to reflect this change.

**Comment by ammgws** [comment]
Didn't realise there was such a breaking change lately! Should definitely be mentioned.. or perhaps reverted sicne not worth breaking everyone's config for it..

**Comment by frazar** [comment]
Yes, reverting sounds more reasonable
