### ISSUE TITLE
Consider joining Hacktoberfest

### ISSUE THREAD

**Issue by frazar** [franciscolourenco/done#120]
More info [here](https://hacktoberfest.digitalocean.com/).

To do so, it should be sufficient to add the `hacktoberfest` label to the GitHub repository.

**Comment by franciscolourenco** [comment]
I was inclined not to join because the quality of PRs last year was not the best, but since you proposed, I've add the topics to the repository. Thanks.

**Comment by frazar** [comment]
Thank you for taking this into considerarlon. I understand last year was a real mess for maintainers, unfortunately. If you feel like the issue is occurring again, I would support you in withdrawing again.
