### ISSUE TITLE
Unexpected and strange error "Unknown command: humanize_duration"

### ISSUE THREAD

**Issue by romanrev** [franciscolourenco/done#122]
After I've upgraded my Fisherman I've started getting this kind of strange error in my terminal after a command finishes. I've already tried removing the `done` plugin and installing it again, but it doesn't seem to help. I cannot find the `humanize_duration` in the `done.fish` file BTW, so not sure how to debug it. Any hints are greatly appreciated!

➤ fish --version
fish, version 3.1.2
➤ fisher --version
fisher, version 4.3.0

```
fish: Unknown command: humanize_duration
~/.config/fish/conf.d/done.fish (line 1): 
echo "$cmd_duration" | humanize_duration
                       ^
in command substitution
	called on line 146 of file ~/.config/fish/conf.d/done.fish
in function '__done_ended'
in event handler: handler for generic event 'fish_prompt'
~/.config/fish/conf.d/done.fish: Unknown error while evaluating command substitution
in function '__done_ended'
in event handler: handler for generic event 'fish_prompt'
```

**Comment by ammgws** [comment]
Looks like you're on an old version of `done`, since that function was internalised in the code quite a while ago.

The error is probably because that package was renamed to `humantime`: https://github.com/jorgebucaran/humantime.fish/

Anyway, updating `done` should resolve your issue

**Comment by romanrev** [comment]
thanks for your prompt feedback @ammgws ! But I have already updated `done`, or so I thought at least, by running `fisher update franciscolourenco/done` - several times already in fact. Could you tell what is the way to confirm the update has actually happened, except for observing the output?
```
➤ fisher update franciscolourenco/done
fisher update version 4.3.0
Fetching https://codeload.github.com/franciscolourenco/done/tar.gz/HEAD
Installing franciscolourenco/done
           /Users/roman/.config/fish/conf.d/done.fish
Updated 1 plugin/s
```
thank you!
