### ISSUE TITLE
Not working on macOS 14.0

### ISSUE THREAD

**Issue by jie17** [franciscolourenco/done#139]
I'm not sure if the specs of `lsappinfo` has changed or not. 
However, in macOS 14.0, `lsappinfo front` returns something like `ASN:0x0-14b14b:`. 
To get the bundle id, the command should be `lsappinfo info -only bundleId 0x14b14b | cut -d '"' -f4`.
`lsappinfo info -only bundleID (lsappinfo front) | cut -d '"' -f4` is not working.

**Comment by franciscolourenco** [comment]
In macOS 13, `lsappinfo front` returns something like `ASN:0x0-14b14b:` as well.
What might have changed is what `lsappinfo info -only bundleID (lsappinfo front)` returns. 
@jie17 could you try that and share? Thanks!

**Comment by franciscolourenco** [comment]
@jie17 I've just tested done on macOS 14.0 and both `done` and the command seem to be working properly. Any ideas?
<img width="750" alt="image" src="https://github.com/franciscolourenco/done/assets/208149/4c3e058c-e275-4e98-b6a7-b1a9ce841d4e">

**Comment by kidonng** [comment]
I'm having the same issue on macOS 14.0 (23A344).

> What might have changed is what `lsappinfo info -only bundleID (lsappinfo front)` returns.

This gives empty result on my machine. In fact `lsappinfo info <ASN>` doesn't work at all (`lsappinfo info <name>` still works though).

**Comment by franciscolourenco** [comment]
@kidonng your proposal works in macOS 13, so we could possibly go with that. I wonder if all apps start with the `0x0` prefix though. Could you try the following two variants and let me know if any of them work?
I would test them myself, but in my VM, the original command is working correctly.

```
lsappinfo info -only bundleID -long (lsappinfo front) | cut -d '"' -f4
```

```
lsappinfo info -only bundleID -app (lsappinfo front) | cut -d '"' -f4
```

Thanks!

**Comment by jie17** [comment]
`lsappinfo info -only bundleID -long (lsappinfo front) | cut -d '"' -f4`

`lsappinfo info -only bundleID -app (lsappinfo front) | cut -d '"' -f4`

Both commands return empty in my environment.

The difference between `0x0-14b14b` and `0x14b14b` seems to be the problem here.

**Comment by jie17** [comment]
`lsappinfo info -only bundleID -long (lsappinfo front) | cut -d '"' -f4`

`lsappinfo info -only bundleID -app (lsappinfo front) | cut -d '"' -f4`

Both commands return nothing in my environment.

Also, by calling`lsappinfo processList`,  I found that all apps start with `0x0:0x`, and then followed by 5 or 6 hex digits.
