### ISSUE TITLE
No protocol specified when using executing the xprop line in done.fish

### ISSUE THREAD

**Issue by c02y** [franciscolourenco/done#27]
https://github.com/fisherman/done/blob/d07eca1cde37303cf63ca8ab4fbb951d883a3f81/conf.d/done.fish#L30

I sourced done.fish in my config.fish, and after every fish prompt, there will be a line of error message:

    No protocol specified

and found the issue is caused by the xprop line:

    xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2

but I'm not familiar with the xprop, after googling a while but didn't get the solution.

FYI:
openSUSE Tumbleweed
fish-shell v2.7.1

**Comment by franciscolourenco** [comment]
@c02y can yuo paste the output of `echo $DISPLAY`? Thanks!

**Comment by c02y** [comment]
$ echo $DISPLAY
    :0

**Comment by franciscolourenco** [comment]
@c02y are you using KDE?

**Comment by c02y** [comment]
Yes.

**Comment by franciscolourenco** [comment]
@c02y Just installed Tumbleweed with KDE and cannot reproduce. What is the result of 

```
echo $XAUTHORITY
cat $XAUTHORITY 
```

?

**Comment by c02y** [comment]
![screenshot_20180402_203446](https://user-images.githubusercontent.com/2135996/38196449-d59c2e66-36b5-11e8-81d2-52aed2bd108f.png)

**Comment by franciscolourenco** [comment]
@c02y can you try what is suggested in this answer? https://unix.stackexchange.com/a/429809

**Comment by c02y** [comment]
It is not working.

And I tried all the answers in that post, none of them works.

**Comment by franciscolourenco** [comment]
That is strange, and I cannot reproduce the problem. Do you have anything unusual in your setup?

**Comment by c02y** [comment]
Unusual? I use the same fish configurations in multiple machines, other machines work fine, but the machine I  mentioned in the top of this thread doesn't work. It is weird.

**Comment by franciscolourenco** [comment]
I meant unusual in the machine itself 😄  like for example, a remote desktop or streaming display something like that.	

Could you try xdotool as described in this answer and see if it works? https://superuser.com/a/615946

**Comment by c02y** [comment]
>> xdotool getwindowfocus getwindowname
    No protocol specified
    chz : tmux — Yakuake

**Comment by c02y** [comment]
No, I tried it without tmux session running, the same result.

After every fish prompt, there will be a line of error message:

    No protocol specified

**Comment by ammgws** [comment]
This issue seems stale. Would you be OK with closing it?

**Comment by franciscolourenco** [comment]
@c02y can you still reproduce the problem?

**Comment by c02y** [comment]
No, the problems is gone, but I'm using another environment now:
Manjaro
fish-shell: v3.0.2

`done` works fine in this environment, and I'm still using the old version of `done`, v1.8.1, this reminds me of updating it.

Thanks for the help.
