### ISSUE TITLE
Default excluded commands

### ISSUE THREAD

**Issue by BarbzYHOOL** [franciscolourenco/done#37]
I suggest to add these commands to the default ignored commands:

    nano vim edit sudoedit ssh top man htop iotop less more

If I find more I'll note them down.

Feel free to discuss them

**Comment by franciscolourenco** [comment]
These are commands which are supposed to terminate while your terminal is in the foreground - in which case the script should not send a notification. 

On the other hand, if a ssh session in the background, you might want to know about 
it.

Do you receive a notifications when run these commands?

**Comment by BarbzYHOOL** [comment]
Hmm you're right, I don't know how but I received notification with some of these commands but I don't remember how and why

**Comment by ammgws** [comment]
Is it safe to close this issue now? I cannot reproduce it either.
