### ISSUE TITLE
Add config for bell sound

### ISSUE THREAD

**Issue by BarbzYHOOL** [franciscolourenco/done#38]
Something like:

	set -l NOTIF_BEEP 1 # Allow beep or not

	# Beep				
	if test "$NOTIF_BEEP" -eq 1
		echo -n \a
	end

(btw the bell sound doesn't work on my computer but that's not fish related)

**Comment by franciscolourenco** [comment]
This is supported with:

```
set -U __done_notify_sound 1
```
