### ISSUE TITLE
Question about test file

### ISSUE THREAD

**Issue by ammgws** [franciscolourenco/done#53]
The file at `test/done.fish` doesn't appear to contain valid fish syntax where the `test` function is used, is this on purpose?

```
function setup
  source conf.d/done.fish
end

test "command are executed without errors"
  0 -eq (echo 1 > /dev/null; echo $status)
end
```

Output:
> /t/d/test >>> fish done.fish
> done.fish (line 7): 'end' outside of a block
> end
> ^
> <W> fish: Error while reading file done.fish

**Comment by franciscolourenco** [comment]
The tests are run with https://github.com/jorgebucaran/fishtape
The syntax seems to be outdated
