### ISSUE TITLE
done.fish invokes the ImageMagick import utility and break everything

### ISSUE THREAD

**Issue by RaitoBezarius** [franciscolourenco/done#74]
Hi there, thank you for your work!

Since the latest version 1.14.1, it seems like done.fish is invoking `import` somewhere and `import` is also known as an ImageMagick tool, blocking the shell, waiting for a GUI input.

I'm not sure if it's related to PowerShell addition because of `Import-Module` or something like this.

Can I give you some help to find this?

Thanks!

**Comment by ammgws** [comment]
If you have fish 3.1, does setting fish_trace to 1 show any useful output?

**Comment by ammgws** [comment]
Actually are you sure it's not the same as this issue:

https://github.com/franciscolourenco/done/commit/5d7f6ae50a9e8c7d1c95af5ad8bfc3155b331fbc#commitcomment-38204903

?

**Comment by RaitoBezarius** [comment]
@ammgws Oh, it *is* the same, most likely indeed.

**Comment by ammgws** [comment]
@RaitoBezarius The latest release should have fixed this, can you confirm?

**Comment by RaitoBezarius** [comment]
@ammgws Tested, it works!
