### ISSUE TITLE
eval: command not found

### ISSUE THREAD

**Issue by minzastro** [franciscolourenco/done#76]
I have this error after the last FISH update (to 3.1).
*done* version 1.14.3
``` eval: command not found                     
~/.config/fish/conf.d/done.fish (line 126): 
                eval $__done_notification_command
                ^
in function “__done_ended”
	called on standard input

in event handler: handler for generic event “fish_prompt”
```

**Comment by ammgws** [comment]
Does $__done_notification_command evaluate to anything?

**Comment by franciscolourenco** [comment]
@minzastro what is the result of 
`echo $__done_notification_command`?

**Comment by franciscolourenco** [comment]
@minzastro at first sight this problem seems to specific to the command that you set in 
`$__done_notification_command`, so this issue will be closed if you don't provide more information.

**Comment by minzastro** [comment]
The problem was with the eval command itself. It disappeared after a reboot. Have no idea what it was, actually.
