### ISSUE TITLE
iTerm and Fish apps on MacOs (Catalina) not triggering the notification

### ISSUE THREAD

**Issue by gm0re** [franciscolourenco/done#89]
After installation, running `sleep 6` does nothing. I tried in both iTerm 2 and Fish apps.

**Comment by bms8197** [comment]
It appears that it works sometimes and some other times it doesn't

For example, using `sleep 30; ping www.yahoo.com` - no notification
if I do: `sudo /usr/libexec/locate.updatedb` (it took like 67 seconds) - I've got a notification using the MacOS notification system.

Operating system: **MacOS Catalina 10.15.7**
Fish version: **3.1.2**
ITerm version: **3.3.12 (latest stable)**

I had to run these commands manually on a new iTerm terminal:
```
source /Users/bogdan/.config/fish/functions/humanize_duration.fish
source /Users/bogdan/.config/fish/conf.d/done.fish
```

**Comment by franciscolourenco** [comment]
@gbrlmoreira any more info you can provide? Still having this problem? Thanks

**Comment by bms8197** [comment]
> @gbrlmoreira any more info you can provide? Still having this problem? Thanks

Not really, it seems it works just fine
