### ISSUE TITLE
Needed to log out

### ISSUE THREAD

**Issue by MrYakobo** [franciscolourenco/done#95]
Hey, thank you for this project. It's a really handy feature to get notifications for long-running commands, it's something I've long wanted to have :heart: 

I had to log out from my sway session to get this to apply. You could maybe add some notice in the readme about that. Something like:

```markdown
## Installation
...
You may also need to log out of your current session.
```

Have a nice day :+1:

**Comment by franciscolourenco** [comment]
@MrYakobo With just fish and fisher it seems to work right away. Can you confirm that this is limited to Sway?
